name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Garante que os testes serão executados em cada commit na branch 'main'
  pull_request:
    branches:
      - main  # Garante que os testes serão executados quando alguém abrir um PR para 'main'

jobs:
  test:
    name: Test on multiple OS and Python versions
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]  # Definindo os sistemas operacionais
        python-version: [3.8, 3.10]  # Versões do Python

    steps:
      # Passo 1: Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Passo 2: Configuração do Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Passo 4: Rodar os testes com pytest
      - name: Run tests
        run: |
          pytest
